apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None  # Headless service
  selector:
    application: mysql
    tier: db_tier
    project: expense
    environment: dev
    created_by: HemanthKumar
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    application: mysql
    tier: db_tier
    project: expense
    environment: dev
    created_by: HemanthKumar
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      application: mysql
      tier: db_tier
      project: expense
      environment: dev
      created_by: HemanthKumar  # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 2 # by default is 1
  # minReadySeconds: 5 # by default is 0
  template:
    metadata:
      labels:
        application: mysql
        tier: db_tier
        project: expense
        environment: dev
        created_by: HemanthKumar     # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: "joindevops/mysql:{{ .Values.deployment.version }}"
        volumeMounts:
        - name: mysql
          mountPath: {{ .Values.deployment.mountpath }} # /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs-sc-dynamic"
      resources:
        requests:
          storage: {{.Values.deployment.storage }}