apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: HemanthKumar
      module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: HemanthKumar
        module: backend
    spec:
      containers:
        - name: backend
          image: "hemanthkumar75/backend:{{ .Values.deployment.version }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 120m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: backend
          # ports:
          #   - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: HemanthKumar
    module: backend
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: {{ .Values.hpa.min_replicas }}
  maxReplicas: {{ .Values.hpa.max_replicas }}
  # targetCPUUtilizationPercentage: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpuutilization }}
